### ISSUE TITLE
US01 - Eu, como usuário (a), desejo ser capaz de selecionar uma váriavel, para que eu possa analisar a variação dos valores dessa váriavel.

### ISSUE THREAD

**Issue by damarcones** [fga-eps-mds/2022-1-Visualeasy-Doc#26]
## Descrição

Permitir a seleção de uma variável para poder criar um gráfico.

## Screenshots

![US01 Screenshot](https://user-images.githubusercontent.com/48698728/181389897-2f67b928-55b2-474d-8c01-d16a034a73c2.png)

## Critérios de aceitação

- [x] Uma variável pode ser selecionada com o mouse;
- [x] Todas as tarefas cumpridas;
- [x] Cobertura de testes em pelo menos 80%.

## Tarefas Back

- [x] Criar a rota que busque todas as váriaveis no Banco de Dados.

## Tarefas Front

- [x] Criar janela de seleção de variáveis;
- [x] Permitir a seleção de uma variável.

**Comment by estevaoreis25** [comment]
Todas as issues dessa história foram finalizadas
